// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: ctx, telegram
func (_m *Cache) GetUser(ctx context.Context, telegram string) ([]byte, error) {
	ret := _m.Called(ctx, telegram)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, telegram)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, telegram)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegram)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVerificationCode provides a mock function with given fields: ctx, telegram
func (_m *Cache) GetVerificationCode(ctx context.Context, telegram string) (int, error) {
	ret := _m.Called(ctx, telegram)

	if len(ret) == 0 {
		panic("no return value specified for GetVerificationCode")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, telegram)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, telegram)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegram)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutUser provides a mock function with given fields: ctx, telegram, userJSON
func (_m *Cache) PutUser(ctx context.Context, telegram string, userJSON []byte) error {
	ret := _m.Called(ctx, telegram, userJSON)

	if len(ret) == 0 {
		panic("no return value specified for PutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, telegram, userJSON)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutVerificationCode provides a mock function with given fields: ctx, telegram, code
func (_m *Cache) PutVerificationCode(ctx context.Context, telegram string, code int) error {
	ret := _m.Called(ctx, telegram, code)

	if len(ret) == 0 {
		panic("no return value specified for PutVerificationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, telegram, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
