// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "github.com/developeerz/restorio-auth/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetUserAuths provides a mock function with given fields: userId
func (_m *Repository) GetUserAuths(userId int64) ([]models.UserAuth, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAuths")
	}

	var r0 []models.UserAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]models.UserAuth, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int64) []models.UserAuth); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
